### PR TITLE
Preserve cursor position

### LINKED ISSUE #4: Spaces are removed when line length is longer than `textwidth`
Thank you for this great plugin. It works great using `gq`. However, I have an issue during typing.

When I exceed the maximum line length, my spaces are removed, and all the words are merged into a single word without spaces. This only happens after the line length is longer than `textwidth`.

### PR DESCRIPTION
**Pull request by whonore**

### CODE REVIEW

**Comment by devarops** [comment]
It works great!

I've tried this out with: `textwidth=100`, `g:sentencer_textwidth=0`, and `g:sentencer_overflow=20`. I wrote 700 words in Markdown, and it worked as expected.

**Comment by devarops** [comment]
You were right about the corner cases. While writing in Spanish, I've found a case that doesn't work. If there is a word with an accent or tilde (á, é, í, ó, ú, ñ) and a word ends exactly at `textwidth`+`overflow`, the line breaks as expected, but we lose a space.

For instance, in this example, we have a "Ó" at the beginning of the line, and the second "Nine" ends exactly at 120 (`textwidth=100` + `sentencer_overflow=20`):

```
Óne Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen Fourteen Fifteen Sixteen Seventeen Eighteen Nine Twenty. 
```

We expect this:
```
Óne Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen Fourteen Fifteen Sixteen
Seventeen Eighteen Nine Twenty. 
```

But we get this:
```
Óne Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen Fourteen Fifteen Sixteen
Seventeen Eighteen NineTwenty. 
```

The last two words are merged without a space between them.

**Comment by devarops** [comment]
Here is another example that doesn't work. Here we have a "Ó" at the beginning, a sentence ending before `textwidth=100`, and the word "six" ending precisely at `textwidth=100`:
```
Óne Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen. One two three four five six seven.
```

We expect:
```
Óne Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen.
One two three four five six seven.
```

However, we get the following:
```
Óne Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve Thirteen.
One two three four five sixseven.
```

Again, the last two words are merged without a space between them.

**Comment by whonore** [comment]
Ah, I thought multi-byte characters might be a problem. Thanks for the test cases, I'll take a look.

**Comment by whonore** [comment]
Sorry for the delay, but the most recent commit should count the length of lines with multi-byte characters correctly.

**Comment by devarops** [comment]
Thank you! I'll check it out.

**Pull request merged**
